### ISSUE TITLE
Custom issue order?

### ISSUE THREAD

**Issue by korody** [TransitScreen/wp-github-pipeline#9]
Hello @emersonthis! Thanks for the very useful plugin.
I'm writting you a message here, because I didn't find any other contact information.

I'm using the plugin in [my company's public page](http://maestru.com.br/novidades/), as public changelog for any bypassers interested in knowing our latest features. 

My issue is that by default, issues are ordered by, obviously, issue id. But in our case, it would make sense to have it ordered by closed_at DESC. Do you believe you could provide an option in the plugin for custom ordering? Or, as an alternative, provide me with directions on how I'd be able to achieve that by adding a couple of lines to your code?

Thank you very much for your support.

**Comment by emersonthis** [comment]
Thanks for your interest. I'll check what options for ordering issues are supported by the github API. If 'closed_at' is supported it shouldn't be hard to implement.

**Comment by korody** [comment]
Great! Thank you very much for your support.

2015-09-25 23:05 GMT-03:00 emersonthis notifications@github.com:

> Thanks for your interest. I'll check what options for ordering issues are
> supported by the github API. If 'closed_at' is supported it shouldn't be
> hard to implement.
> 
> > On Sep 25, 2015, at 10:43 AM, Marcos Korody notifications@github.com
> > wrote:
> > 
> > Hello @emersonthis! Thanks for the very useful plugin.
> > I'm writting you a message here, because I didn't find any other contact
> > information.
> > 
> > I'm using the plugin in my company's public page, as public changelog
> > for any bypassers interested in knowing our latest features.
> > 
> > My issue is that by default, issues are ordered by, obviously, issue id.
> > But in our case, it would make sense to have it ordered by closed_at DESC.
> > Do you believe you could provide an option in the plugin for custom
> > ordering? Or, as an alternative, provide me with directions on how I'd be
> > able to achieve that by adding a couple of lines to your code?
> > 
> > Thank you very much for your support.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TransitScreen/wp-github-pipeline/issues/9#issuecomment-143391161
> .

## 

marcos k.
AEROGAMI http://www.aerogami.com.br

**Comment by emersonthis** [comment]
I checked the GitHub API docs and the two relevant endpoints ([/repos/:owner/:repo/issues](https://developer.github.com/v3/issues/#list-issues-for-a-repository), [/orgs/:org/issues](https://developer.github.com/v3/issues/#list-issues)) only offer the option to "sort" issues by: `created`, `updated`, or `comments`. I think those three should already work, but it doesn't sound like they'll achieve the exact functionality you're looking for.

I think the most versatile, and robust way to add the kind of functionality that you're looking for would be to add some kind of `custom_issue_sort` hook to the plugin which you could use to add your own custom sorting algorithm. It might be tricky to get it to play nice with pagination, but if I can figure it out would something like that suite you?

**Comment by korody** [comment]
Hello there. How is it going Emerson?

Thank you very much for looking into that. That would definitely suit my
needs.
Appreciate your effort!

2015-10-09 18:17 GMT-03:00 emersonthis notifications@github.com:

> I checked the GitHub API docs and the two relevant endpoints (
> /repos/:owner/:repo/issues
> https://developer.github.com/v3/issues/#list-issues-for-a-repository,
> /orgs/:org/issues https://developer.github.com/v3/issues/#list-issues)
> only offer the option to "sort" issues by: created, updated, or comments.
> I think those three should already work, but it doesn't sound like they'll
> achieve the exact functionality you're looking for.
> 
> I think the most versatile, and robust way to add the kind of
> functionality that you're looking for would be to add some kind of
> custom_issue_sort hook to the plugin which you could use to add your own
> custom sorting algorithm. It might be tricky to get it to play nice with
> pagination, but if I can figure it out would something like that suite you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TransitScreen/wp-github-pipeline/issues/9#issuecomment-146988035
> .

## 

marcos k.
AEROGAMI http://www.aerogami.com.br

**Comment by emersonthis** [comment]
Just pushed v1.2.2 which adds a `github_issues_list` filter for issues. Note that currently it only applies to the issues list when it's unpaginated.

Something like the following in your theme's functions.php should achieve the result you were asking about:

```
        add_filter('github_issue_list', 'filter_github_issues_list');

        function filter_github_issues_list($issues)
        {
            usort($issues, 'check_created_at');
            return $issues;
        }

        function check_created_at($a, $b)
        {
            if ($a['created_at'] == $b['created_at']){
                return 0;
            }
            return ($a['created_at'] < $b['created_at']) ? -1 : 1;
        }
```
